[package]
name = "hangar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
requestty = "0.1.0"
titlecase = "1.0"
home = "0.5.3"
log = "0.4.14"
env_logger = "0.9.0"